// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBnvze4MQ1VOeqg7rZi0TJNlitcjlRfgY',
    appId: '1:4970882319:web:039372237a9cf207788a7a',
    messagingSenderId: '4970882319',
    projectId: 'tsms-57bc6',
    authDomain: 'tsms-57bc6.firebaseapp.com',
    databaseURL: 'https://tsms-57bc6-default-rtdb.firebaseio.com',
    storageBucket: 'tsms-57bc6.appspot.com',
    measurementId: 'G-Y8GHL22SBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjk4glVa5gE8-02yOSQye09ZTtmlVw1eA',
    appId: '1:4970882319:android:4d1c1ebcd38f20eb788a7a',
    messagingSenderId: '4970882319',
    projectId: 'tsms-57bc6',
    databaseURL: 'https://tsms-57bc6-default-rtdb.firebaseio.com',
    storageBucket: 'tsms-57bc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlq1KraOffpQmKJ1aICtUm3EUYgI20uiE',
    appId: '1:4970882319:ios:7b9262c7f09fb95d788a7a',
    messagingSenderId: '4970882319',
    projectId: 'tsms-57bc6',
    databaseURL: 'https://tsms-57bc6-default-rtdb.firebaseio.com',
    storageBucket: 'tsms-57bc6.appspot.com',
    iosBundleId: 'com.karzan.tsmsAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlq1KraOffpQmKJ1aICtUm3EUYgI20uiE',
    appId: '1:4970882319:ios:a1fdeb7e3720ab38788a7a',
    messagingSenderId: '4970882319',
    projectId: 'tsms-57bc6',
    databaseURL: 'https://tsms-57bc6-default-rtdb.firebaseio.com',
    storageBucket: 'tsms-57bc6.appspot.com',
    iosBundleId: 'com.karzan.tsmsAdmin.RunnerTests',
  );
}
